export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CREATE_ACCOUNT_SUCCESS = 'AUTH_CREATE_ACCOUNT_SUCCESS';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const AUTH_ADMIN_PATCH_SUCCESS = 'AUTH_ADMIN_PATCH_SUCCESS';
export const AUTH_RECOVER_PASSWORD_SUCCESS = 'AUTH_RECOVER_PASSWORD_SUCCESS';
export const AUTH_FINISH = 'AUTH_FINISH';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_STATE_RESET = 'AUTH_STATE_RESET';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';
export const AUTH_ERROR_RESET = 'AUTH_ERROR_RESET';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// access request types
export const ACCESS_REQUEST_START = 'ACCESS_REQUEST_START';
export const USER_CREATE_ACCESS_REQUEST_SUCCESS = 'USER_CREATE_ACCESS_REQUEST_SUCCESS';
export const USER_UPDATE_ACCESS_REQUEST_SUCCESS = 'USER_UPDATE_ACCESS_REQUEST_SUCCESS';
export const PLANNER_UPDATE_ACCESS_REQUEST_SUCCESS = 'PLANNER_UPDATE_ACCESS_REQUEST_SUCCESS';
export const USER_GET_ACCESS_REQUESTS_SUCCESS = 'USER_GET_ACCESS_REQUESTS_SUCCESS';
export const USER_GET_ACCESS_REQUEST_SUCCESS = 'USER_GET_ACCESS_REQUEST_SUCCESS';
export const USER_UPLOAD_ACCESS_REQUEST_DOCUMENT_SUCCESS = 'USER_UPLOAD_ACCESS_REQUEST_DOCUMENT_SUCCESS';
export const USER_DELETE_ACCESS_REQUEST_DOCUMENT_SUCCESS = 'USER_DELETE_ACCESS_REQUEST_DOCUMENT_SUCCESS'
export const PLANNER_GET_ACCESS_REQUESTS_SUCCESS = 'PLANNER_GET_ACCESS_REQUESTS_SUCCESS';
export const ACCESS_REQUEST_PLANNER_GET_PLANNERS_SUCCESS = 'ACCESS_REQUESTS_GET_PLANNERS_SUCCESS';
export const ACCESS_REQUEST_PLANNER_DELETE_SUCCESS = 'ACCESS_REQUEST_DELETE_SUCCESS';
export const ACCESS_REQUEST_FINISH = 'ACCESS_REQUEST_FINISH';
export const ACCESS_REQUEST_FAIL = 'ACCESS_REQUEST_FAIL';
export const ACCESS_REQUEST_STATE_RESET = 'ACCESS_REQUEST_STATE_RESET';
export const ACCESS_REQUEST_REDIRECT_PATH = 'ACCESS_REQUEST_REDIRECT_PATH';
export const ACCESS_REQUEST_ERROR_RESET = 'ACCESS_REQUEST_ERROR_RESET';

export const PUBLIC_VIEW_START = 'PUBLIC_VIEW_START';
export const PUBLIC_VIEW_SUCCESS = 'PUBLIC_VIEW_SUCCESS';
export const PUBLIC_VIEW_FINISH = 'PUBLIC_VIEW_FINISH';
export const PUBLIC_VIEW_FAIL = 'PUBLIC_VIEW_FAIL';
export const PUBLIC_VIEW_STATE_RESET = 'PUBLIC_VIEW_STATE_RESET';
export const PUBLIC_VIEW_ERROR_RESET = 'PUBLIC_VIEW_ERROR_RESET';

export const DISRUPTIVE_START = 'DISRUPTIVE_START';
export const DISRUPTIVE_CREATE_SUCCESS = 'DISRUPTIVE_CREATE_SUCCESS';
export const DISRUPTIVE_UPDATE_SUCCESS = 'DISRUPTIVE_UPDATE_SUCCESS';
export const DISRUPTIVES_GET_SUCCESS = 'DISRUPTIVES_GET_SUCCESS';
export const DISRUPTIVE_GET_SUCCESS = 'DISRUPTIVE_GET_SUCCESS';
export const DISRUPTIVE_SELECT_SUCCESS = 'DISRUPTIVE_SELECT_SUCCESS';
export const DISRUPTIVE_FINISH = 'DISRUPTIVE_FINISH';
export const DISRUPTIVE_FAIL = 'DISRUPTIVE_FAIL';
export const DISRUPTIVE_STATE_RESET = 'DISRUPTIVE_STATE_RESET';
export const DISRUPTIVE_ERROR_RESET = 'DISRUPTIVE_ERROR_RESET';

export const SPEED_RESTRICTION_START = 'SPEED_RESTRICTION_START';
export const SPEED_RESTRICTION_CREATE_SUCCESS = 'SPEED_RESTRICTION_CREATE_SUCCESS';
export const SPEED_RESTRICTIONS_GET_SUCCESS = 'SPEED_RESTRICTIONS_GET_SUCCESS';
export const SPEED_RESTRICTION_GET_SUCCESS = 'SPEED_RESTRICTION_GET_SUCCESS';
export const SPEED_RESTRICTION_UPDATE_SUCCESS = 'SPEED_RESTRICTION_UPDATE_SUCCESS';
export const SPEED_RESTRICTION_FINISH = 'SPEED_RESTRICTION_FINISH';
export const SPEED_RESTRICTION_FAIL = 'SPEED_RESTRICTION_FAIL';
export const SPEED_RESTRICTION_STATE_RESET = 'SPEED_RESTRICTION_STATE_RESET';
export const SPEED_RESTRICTION_REDIRECT_PATH = 'SPEED_RESTRICTION_REDIRECT_PATH';